Traceback (most recent call last):
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
L = 20
myfilter = Filtro_NLMS(L=20, mu=0.02)
w = np.zeros()
for k in range(L+1, len(u)):
    u_pred[k, i] = myfilter.update(u[k-L-1:k][::-1], u[k])
        
fk, Hk = scipy.signal.freqz(b=myfilter.w, a=1, fs=Fs)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-10-14d3645b16a8>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mL[0m [0;34m=[0m [0;36m20[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mmyfilter[0m [0;34m=[0m [0mFiltro_NLMS[0m[0;34m([0m[0mL[0m[0;34m=[0m[0;36m20[0m[0;34m,[0m [0mmu[0m[0;34m=[0m[0;36m0.02[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mw[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mzeros[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;32mfor[0m [0mk[0m [0;32min[0m [0mrange[0m[0;34m([0m[0mL[0m[0;34m+[0m[0;36m1[0m[0;34m,[0m [0mlen[0m[0;34m([0m[0mu[0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0mu_pred[0m[0;34m[[0m[0mk[0m[0;34m,[0m [0mi[0m[0;34m][0m [0;34m=[0m [0mmyfilter[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0mu[0m[0;34m[[0m[0mk[0m[0;34m-[0m[0mL[0m[0;34m-[0m[0;36m1[0m[0;34m:[0m[0mk[0m[0;34m][0m[0;34m[[0m[0;34m:[0m[0;34m:[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m,[0m [0mu[0m[0;34m[[0m[0mk[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: zeros() missing required argument 'shape' (pos 1)
TypeError: zeros() missing required argument 'shape' (pos 1)

