Traceback (most recent call last):
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Estimador de minimos cuadrados para filtro FIR usando scipy.signal
h = scipy.signal.firls(numtaps=1000+1, 
                       bands=(0., 640, 650, 2340, 2350, 2750, 2760, sample_rate//2), 
                       desired=(5., 5., 0., 0., 1., 1., 0., 0.), fs=sample_rate)

plt.close('all'); fig = plt.figure(figsize=(8, 6))
ax1 = plt.subplot2grid((2, 2 ), (0, 0)); ax1.set_title("Respuesta al impulso")
ax2 = plt.subplot2grid((2, 2 ), (0, 1)); ax2.set_title("Respuesta en frecuencia")
ax3 = plt.subplot2grid((2, 2 ), (1, 0), colspan=2, rowspan=1)

freq, response = scipy.signal.freqz(h)
ax1.plot(h); ax2.semilogy(0.5*sample_rate*freq/np.pi, np.abs(response));
data_filt = scipy.signal.convolve(data, h)
freq, ttime, Sxx = scipy.signal.spectrogram(data_filt, fs=sample_rate, window=('tukey', 0.25), 
                                            nperseg=256, noverlap=None, detrend=False,
                                            return_onesided=True, scaling='density', mode='magnitude')
ax3.pcolormesh(ttime, freq, 20*np.log10(Sxx+1e-4), cmap=plt.cm.magma); ax3.set_ylim([0.0, 1e+4]);
Audio(data_filt, rate=int(sample_rate))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-890099b4022d>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Estimador de minimos cuadrados para filtro FIR usando scipy.signal[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m h = scipy.signal.firls(numtaps=1000+1, 
[0m[1;32m      3[0m                        [0mbands[0m[0;34m=[0m[0;34m([0m[0;36m0.[0m[0;34m,[0m [0;36m640[0m[0;34m,[0m [0;36m650[0m[0;34m,[0m [0;36m2340[0m[0;34m,[0m [0;36m2350[0m[0;34m,[0m [0;36m2750[0m[0;34m,[0m [0;36m2760[0m[0;34m,[0m [0msample_rate[0m[0;34m//[0m[0;36m2[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m                        desired=(5., 5., 0., 0., 1., 1., 0., 0.), fs=sample_rate)
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'scipy' is not defined
NameError: name 'scipy' is not defined

